{% set title = title|default('500 - Internal Server Error') %}
{% extends "base.html" %}
{% block metadata %}
<meta property="og:type" content="website">
<meta property="og:title" content="{{ config['SERVICE'] }}: Home">
<meta property="og:description" content="The server fainted. What were you doing? （*゜ー゜*）">
<meta property="og:image" content="{{ url_for('static', filename='music.png', _external=true) }}">
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="{{ config['HOST_URL'] }}">
<meta name="twitter:title" content="{{ config['SERVICE'] }}: Home">
<meta name="twitter:description" content="The server fainted. What were you doing? （*゜ー゜*）">
<meta name="twitter:image" content="{{ url_for('static', filename='music.png', _external=true) }}">
{% endblock %}

{% block header %}
<h1>{{ title }}</h1>
{% endblock %}

{% block content %}
<main class="container">
    <div class="grid error-container">
        <img class="error-img" src="{{ url_for('static', filename='errors/500.gif') }}" alt="anime-satania"
            width="500px">
        <div>
            <p>Oops~ the server fainted. Why not go back <a href="{{ url_for('main.index') }}">Home</a>?</p>
            <p>If this keep happening, feel free to open an issue on Github
                <a href="https://github.com/CheapNightbot/yutify/issues">HERE</a> !
                Make sure to provide the input that caused this error.
            </p>
        </div>
    </div>
</main>
{% endblock %}
